// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leaf.protopackage org.paboo.leaf.proto;

public final class LeafProto {
  private LeafProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_paboo_leaf_proto_LeafReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_paboo_leaf_proto_LeafReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_paboo_leaf_proto_LeafResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_paboo_leaf_proto_LeafResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_paboo_leaf_proto_LeafMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_paboo_leaf_proto_LeafMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nleaf.proto\022\024org.paboo.leaf.proto\",\n\007Le" +
      "afReq\022\016\n\006nodeId\030\001 \001(\005\022\021\n\tserviceId\030\002 \001(\005" +
      "\"\026\n\010LeafResp\022\n\n\002id\030\001 \001(\003\"\032\n\007LeafMsg\022\017\n\007m" +
      "essage\030\001 \001(\t2\241\001\n\013LeafService\022H\n\005IdGen\022\035." +
      "org.paboo.leaf.proto.LeafReq\032\036.org.paboo" +
      ".leaf.proto.LeafResp\"\000\022H\n\005IdPar\022\036.org.pa" +
      "boo.leaf.proto.LeafResp\032\035.org.paboo.leaf" +
      ".proto.LeafMsg\"\000B&\n\024org.paboo.leaf.proto" +
      "B\tLeafProtoP\001\210\001\001b\006proto3"
    };
    internal_static_org_paboo_leaf_proto_LeafReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_paboo_leaf_proto_LeafReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_paboo_leaf_proto_LeafReq_descriptor,
        new String[] { "NodeId", "ServiceId", });
    internal_static_org_paboo_leaf_proto_LeafResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_paboo_leaf_proto_LeafResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_paboo_leaf_proto_LeafResp_descriptor,
        new String[] { "Id", });
    internal_static_org_paboo_leaf_proto_LeafMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_paboo_leaf_proto_LeafMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_paboo_leaf_proto_LeafMsg_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
