// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leaf.protopackage org.paboo.leaf.proto;

public interface LeafReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.paboo.leaf.proto.LeafReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeId = 1;</code>
   * @return The nodeId.
   */
  int getNodeId();

  /**
   * <code>int32 serviceId = 2;</code>
   * @return The serviceId.
   */
  int getServiceId();
}
