driver:
  name: OpcUaDriver
  description: @project.description@
  schedule:
    read:
      enable: true
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn:  '0/5 * * * * ?'
  driver-attribute:
    - displayName: 主机
      name: host
      type: string
      value: localhost
      description: Opc Ua IP
    - displayName: 端口
      name: port
      type: int
      value: 18600
      description: Opc Ua Port
    - displayName: 路径
      name: path
      type: string
      value: /
      description: Opc Ua Path
  point-attribute:
    - displayName: 命名空间
      name: namespace
      type: int
      value: 5
      description: 命名空间索引
    - displayName: 位号
      name: tag
      type: string
      value: TAG
      description: 位号名称

server:
  port: 8603

spring:
  application:
    name: @project.artifactId@

logging:
  level:
    org.springclouddev.iot.driver: DEBUG
    org.springclouddev.iot.common.sdk: DEBUG
  file:
    name: iot/logs/driver/opcua/${spring.application.name}.log