spring:
  jpa:
    show-sql: false
    database-platform: org.dbchain.blockchain.core.sqlite.config.SQLiteDialect
    generate-ddl: true
sqlite:
  dbName: dbchain.db  #本地sqlite的名字
db:
  levelDB: true    #在部分Windows机器上rocksDB会报错dll找不到，那么就用levelDB来替代
  rocksDB: false
singleNode: true  #如果是单节点测试，改成true
version: 1
name: ${NAME:maida}
appId: ${APP_ID:wolf}
managerUrl: ${MANAGER_URL:http://localhost:8181/}
publicKey: A/XPlwP7beLREu4r0+s+vE6kUY+XsaAH5Ye6x1R0d46r
privateKey: cOSq0Rul8xppftOGDT3F2l1xVuFhcBkb2tsNETClADI=
