driver:
  name: ModbusDriver
  description: @project.description@
  schedule:
    read:
      enable: true
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn:  '0/5 * * * * ?'
  driver-attribute:
    - displayName: 主机
      name: host
      type: string
      value: localhost
      description: Modbus IP
    - displayName: 端口
      name: port
      type: int
      value: 502
      description: Modbus Port
  point-attribute:
    - displayName: 从站编号
      name: slaveId
      type: int
      value: 1
      description: 从站编号
    - displayName: 功能码
      name: functionCode
      type: int
      value: 1
      description: 功能码 [1、2、3、4]
    - displayName: 偏移量
      name: offset
      type: int
      value: 0
      description: 偏移量

server:
  port: 8604

spring:
  application:
    name: @project.artifactId@

logging:
  level:
    org.springclouddev.iot.driver: DEBUG
    org.springclouddev.iot.common.sdk: DEBUG
  file:
    name: iot/logs/driver/modbus/${spring.application.name}.log