#服务器端口
server:
  port: 8501

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx

# seata配置
seata:
  registry:
    type: nacos
   nacos:
      server-addr: localhost
  config:
    type: nacos
    nacos:
      server-addr: localhost
  tx-service-group: mk-seata-order-group
  service:
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      mk-seata-order-group: defhibernate-validatorault
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false