// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leaf.proto

package org.paboo.leaf.proto;

/**
 * <pre>
 * The leaf service definition
 * </pre>
 *
 * Protobuf service {@code org.paboo.leaf.proto.LeafService}
 */
public  abstract class LeafService
    implements com.google.protobuf.Service {
  protected LeafService() {}

  public interface Interface {
    /**
     * <code>rpc IdGen(.org.paboo.leaf.proto.LeafReq) returns (.org.paboo.leaf.proto.LeafResp);</code>
     */
    public abstract void idGen(
            com.google.protobuf.RpcController controller,
            LeafReq request,
            com.google.protobuf.RpcCallback<LeafResp> done);

    /**
     * <code>rpc IdPar(.org.paboo.leaf.proto.LeafResp) returns (.org.paboo.leaf.proto.LeafMsg);</code>
     */
    public abstract void idPar(
            com.google.protobuf.RpcController controller,
            LeafResp request,
            com.google.protobuf.RpcCallback<LeafMsg> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new LeafService() {
      @Override
      public  void idGen(
          com.google.protobuf.RpcController controller,
          LeafReq request,
          com.google.protobuf.RpcCallback<LeafResp> done) {
        impl.idGen(controller, request, done);
      }

      @Override
      public  void idPar(
          com.google.protobuf.RpcController controller,
          LeafResp request,
          com.google.protobuf.RpcCallback<LeafMsg> done) {
        impl.idPar(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.idGen(controller, (LeafReq)request);
          case 1:
            return impl.idPar(controller, (LeafResp)request);
          default:
            throw new AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return LeafReq.getDefaultInstance();
          case 1:
            return LeafResp.getDefaultInstance();
          default:
            throw new AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return LeafResp.getDefaultInstance();
          case 1:
            return LeafMsg.getDefaultInstance();
          default:
            throw new AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc IdGen(.org.paboo.leaf.proto.LeafReq) returns (.org.paboo.leaf.proto.LeafResp);</code>
   */
  public abstract void idGen(
      com.google.protobuf.RpcController controller,
      LeafReq request,
      com.google.protobuf.RpcCallback<LeafResp> done);

  /**
   * <code>rpc IdPar(.org.paboo.leaf.proto.LeafResp) returns (.org.paboo.leaf.proto.LeafMsg);</code>
   */
  public abstract void idPar(
      com.google.protobuf.RpcController controller,
      LeafResp request,
      com.google.protobuf.RpcCallback<LeafMsg> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return LeafProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.idGen(controller, (LeafReq)request,
          com.google.protobuf.RpcUtil.<LeafResp>specializeCallback(
            done));
        return;
      case 1:
        this.idPar(controller, (LeafResp)request,
          com.google.protobuf.RpcUtil.<LeafMsg>specializeCallback(
            done));
        return;
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return LeafReq.getDefaultInstance();
      case 1:
        return LeafResp.getDefaultInstance();
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return LeafResp.getDefaultInstance();
      case 1:
        return LeafMsg.getDefaultInstance();
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends LeafService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void idGen(
        com.google.protobuf.RpcController controller,
        LeafReq request,
        com.google.protobuf.RpcCallback<LeafResp> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        LeafResp.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          LeafResp.class,
          LeafResp.getDefaultInstance()));
    }

    public  void idPar(
        com.google.protobuf.RpcController controller,
        LeafResp request,
        com.google.protobuf.RpcCallback<LeafMsg> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        LeafMsg.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          LeafMsg.class,
          LeafMsg.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public LeafResp idGen(
            com.google.protobuf.RpcController controller,
            LeafReq request)
        throws com.google.protobuf.ServiceException;

    public LeafMsg idPar(
            com.google.protobuf.RpcController controller,
            LeafResp request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public LeafResp idGen(
        com.google.protobuf.RpcController controller,
        LeafReq request)
        throws com.google.protobuf.ServiceException {
      return (LeafResp) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        LeafResp.getDefaultInstance());
    }


    public LeafMsg idPar(
        com.google.protobuf.RpcController controller,
        LeafResp request)
        throws com.google.protobuf.ServiceException {
      return (LeafMsg) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        LeafMsg.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:org.paboo.leaf.proto.LeafService)
}

