driver:
  name: OpcDaDriver
  description: @project.description@
  schedule:
    read:
      enable: true
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn:  '0/5 * * * * ?'
  driver-attribute:
    - displayName: 主机
      name: host
      type: string
      value: localhost
      description: Opc Da Host
    - displayName: CLSID
      name: clsId
      type: string
      value: F8582CF2-88FB-11D0-B850-00C0F0104305
      description: Opc Da Server CLAID
    - displayName: 用户名
      name: username
      type: string
      value: dc3
      description: Opc Da UserName
    - displayName: 密码
      name: password
      type: string
      value: dc3dc3
      description: Opc Da Passward
  point-attribute:
    - displayName: 分组
      name: group
      type: string
      value: GROUP
      description: 分组名称
    - displayName: 位号
      name: tag
      type: string
      value: TAG
      description: 位号名称

server:
  port: 8602

spring:
  application:
    name: @project.artifactId@

logging:
  level:
    com.freud.dcom.utgard.cases.*: INFO
    com.dc3.common.sdk: DEBUG
    com.dc3: DEBUG
  file:
    name: dc3/logs/driver/opcda/${spring.application.name}.log