##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  自定义配置  ###################
common:
  csvVtoll: /var/csv/
  csvCanton: /var/csv/
  csvExeOffice: /var/csv/
  csvApp: /var/csv/
  csvLog: /var/csv/

###################  spring配置  ###################
spring:
  profiles:
    active: test
  batch:
    schema: classpath:org/springframework/batch/core/schema-mysql.sql
    job:
      enabled: false
    initializer:
      enable: false
    table-prefix: batch_
  integration:
    jdbc:
      initialize-schema: always

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/xncoding/trans/dao/repository/mapping/*.xml
  typeAliasesPackage: >
    com.springbootexample.trans.dao.entity
  global-config:
    id-type: 1  # 0:数据库ID自增  1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    jdbcTypeForNull: NULL
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbatch?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx

common:
  location: 1
  csvDir: E:/

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: /var/logs/batch.log

---

#####################################################################
########################  测试环境profile  ##########################
#####################################################################
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbatch?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx
  main:
    allow-bean-definition-overriding: true
common:
  csvDir: /var/csv/
  location: 2

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: /var/logs/batch.log

