### 查询 Driver Dictionary
#/manager/dictionary/driver
GET http://localhost:8400/manager/dictionary/driver
Accept: */*
Cache-Control: no-cache


### 查询 PointAttribute Dictionary
#/manager/dictionary/pointAttribute
GET http://localhost:8400/manager/dictionary/pointAttribute
Accept: */*
Cache-Control: no-cache


### 查询 Profile Dictionary
#/manager/dictionary/profile
GET http://localhost:8400/manager/dictionary/profile
Accept: */*
Cache-Control: no-cache


### 查询 Group Dictionary
#/manager/dictionary/group
GET http://localhost:8400/manager/dictionary/group
Accept: */*
Cache-Control: no-cache


### 查询 Device/group Dictionary
#/manager/dictionary/device/group
GET http://localhost:8400/manager/dictionary/device/group
Accept: */*
Cache-Control: no-cache


### 查询 Device/driver Dictionary
#/manager/dictionary/device/driver
GET http://localhost:8400/manager/dictionary/device/driver
Accept: */*
Cache-Control: no-cache


### 查询 Device/profile Dictionary
#/manager/dictionary/device/profile
GET http://localhost:8400/manager/dictionary/device/profile
Accept: */*
Cache-Control: no-cache


### 查询 Point/profile Dictionary
#/manager/dictionary/point/profile
GET http://localhost:8400/manager/dictionary/point/profile
Accept: */*
Cache-Control: no-cache


### 查询 Point/device Dictionary
#/manager/dictionary/point/device
GET http://localhost:8400/manager/dictionary/point/device
Accept: */*
Cache-Control: no-cache

###