server:
  port: 8400

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    database: 2
  cache:
    redis:
      time-to-live: 60S

logging:
  level:
    com.dc3: DEBUG
  file:
    name: dc3/logs/center/${spring.application.name}.log

# 用于在分布式部署 driver 情况下，driver 不在 docker 中启动
#eureka:
#  instance:
#    ip-address: 192.168.100.6