// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.acupt.grpc.proto;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acupt_grpc_InvokeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acupt_grpc_InvokeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acupt_grpc_InvokeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acupt_grpc_InvokeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\016com.acupt.grpc\"\035\n\rInvokeRe" +
      "quest\022\014\n\004name\030\001 \001(\t\"\035\n\016InvokeResponse\022\013\n" +
      "\003msg\030\001 \001(\t2X\n\014HelloService\022H\n\005hello\022\035.co" +
      "m.acupt.grpc.InvokeRequest\032\036.com.acupt.g" +
      "rpc.InvokeResponse\"\000B$\n\024com.acupt.grpc.p" +
      "rotoB\nHelloProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_acupt_grpc_InvokeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_acupt_grpc_InvokeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acupt_grpc_InvokeRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_acupt_grpc_InvokeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_acupt_grpc_InvokeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acupt_grpc_InvokeResponse_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
