// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.acupt.grpc.proto;

public interface InvokeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acupt.grpc.InvokeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
