// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.acupt.grpc.proto;

public interface InvokeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acupt.grpc.InvokeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
